// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: common.proto

package scale_handler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Replicas      int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TimeRange) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TimeRange) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type Schedule struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Weekdays      map[string]*Schedule_DaySchedule `protobuf:"bytes,1,rep,name=weekdays,proto3" json:"weekdays,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dates         map[string]*Schedule_DaySchedule `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Exceptions    []string                         `protobuf:"bytes,3,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Schedule) GetWeekdays() map[string]*Schedule_DaySchedule {
	if x != nil {
		return x.Weekdays
	}
	return nil
}

func (x *Schedule) GetDates() map[string]*Schedule_DaySchedule {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *Schedule) GetExceptions() []string {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

type Schedule_DaySchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRanges    []*TimeRange           `protobuf:"bytes,1,rep,name=time_ranges,json=timeRanges,proto3" json:"time_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule_DaySchedule) Reset() {
	*x = Schedule_DaySchedule{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_DaySchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_DaySchedule) ProtoMessage() {}

func (x *Schedule_DaySchedule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule_DaySchedule.ProtoReflect.Descriptor instead.
func (*Schedule_DaySchedule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Schedule_DaySchedule) GetTimeRanges() []*TimeRange {
	if x != nil {
		return x.TimeRanges
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\fscalehandler\"K\n" +
	"\tTimeRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\"\xad\x03\n" +
	"\bSchedule\x12@\n" +
	"\bweekdays\x18\x01 \x03(\v2$.scalehandler.Schedule.WeekdaysEntryR\bweekdays\x127\n" +
	"\x05dates\x18\x02 \x03(\v2!.scalehandler.Schedule.DatesEntryR\x05dates\x12\x1e\n" +
	"\n" +
	"exceptions\x18\x03 \x03(\tR\n" +
	"exceptions\x1aG\n" +
	"\vDaySchedule\x128\n" +
	"\vtime_ranges\x18\x01 \x03(\v2\x17.scalehandler.TimeRangeR\n" +
	"timeRanges\x1a_\n" +
	"\rWeekdaysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".scalehandler.Schedule.DayScheduleR\x05value:\x028\x01\x1a\\\n" +
	"\n" +
	"DatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".scalehandler.Schedule.DayScheduleR\x05value:\x028\x01B+Z)proxy-gateway/pkg/api/proto/scale-handlerb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_goTypes = []any{
	(*TimeRange)(nil),            // 0: scalehandler.TimeRange
	(*Schedule)(nil),             // 1: scalehandler.Schedule
	(*Schedule_DaySchedule)(nil), // 2: scalehandler.Schedule.DaySchedule
	nil,                          // 3: scalehandler.Schedule.WeekdaysEntry
	nil,                          // 4: scalehandler.Schedule.DatesEntry
}
var file_common_proto_depIdxs = []int32{
	3, // 0: scalehandler.Schedule.weekdays:type_name -> scalehandler.Schedule.WeekdaysEntry
	4, // 1: scalehandler.Schedule.dates:type_name -> scalehandler.Schedule.DatesEntry
	0, // 2: scalehandler.Schedule.DaySchedule.time_ranges:type_name -> scalehandler.TimeRange
	2, // 3: scalehandler.Schedule.WeekdaysEntry.value:type_name -> scalehandler.Schedule.DaySchedule
	2, // 4: scalehandler.Schedule.DatesEntry.value:type_name -> scalehandler.Schedule.DaySchedule
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
