// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: service.proto

package scale_handler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\fscalehandler\x1a\x0fcontracts.proto2\xdf\x02\n" +
	"\x13ScaleHandlerService\x12C\n" +
	"\x06Create\x12\x1b.scalehandler.CreateRequest\x1a\x1c.scalehandler.CreateResponse\x12=\n" +
	"\x04List\x12\x19.scalehandler.ListRequest\x1a\x1a.scalehandler.ListResponse\x12:\n" +
	"\x03Get\x12\x18.scalehandler.GetRequest\x1a\x19.scalehandler.GetResponse\x12C\n" +
	"\x06Update\x12\x1b.scalehandler.UpdateRequest\x1a\x1c.scalehandler.UpdateResponse\x12C\n" +
	"\x06Delete\x12\x1b.scalehandler.DeleteRequest\x1a\x1c.scalehandler.DeleteResponseB+Z)scale-handler/pkg/api/proto/scale-handlerb\x06proto3"

var file_service_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: scalehandler.CreateRequest
	(*ListRequest)(nil),    // 1: scalehandler.ListRequest
	(*GetRequest)(nil),     // 2: scalehandler.GetRequest
	(*UpdateRequest)(nil),  // 3: scalehandler.UpdateRequest
	(*DeleteRequest)(nil),  // 4: scalehandler.DeleteRequest
	(*CreateResponse)(nil), // 5: scalehandler.CreateResponse
	(*ListResponse)(nil),   // 6: scalehandler.ListResponse
	(*GetResponse)(nil),    // 7: scalehandler.GetResponse
	(*UpdateResponse)(nil), // 8: scalehandler.UpdateResponse
	(*DeleteResponse)(nil), // 9: scalehandler.DeleteResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: scalehandler.ScaleHandlerService.Create:input_type -> scalehandler.CreateRequest
	1, // 1: scalehandler.ScaleHandlerService.List:input_type -> scalehandler.ListRequest
	2, // 2: scalehandler.ScaleHandlerService.Get:input_type -> scalehandler.GetRequest
	3, // 3: scalehandler.ScaleHandlerService.Update:input_type -> scalehandler.UpdateRequest
	4, // 4: scalehandler.ScaleHandlerService.Delete:input_type -> scalehandler.DeleteRequest
	5, // 5: scalehandler.ScaleHandlerService.Create:output_type -> scalehandler.CreateResponse
	6, // 6: scalehandler.ScaleHandlerService.List:output_type -> scalehandler.ListResponse
	7, // 7: scalehandler.ScaleHandlerService.Get:output_type -> scalehandler.GetResponse
	8, // 8: scalehandler.ScaleHandlerService.Update:output_type -> scalehandler.UpdateResponse
	9, // 9: scalehandler.ScaleHandlerService.Delete:output_type -> scalehandler.DeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_contracts_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
